using System.Security.Cryptography;
using System.Text;

namespace ControleFinanceiroForms.Data.Entities;

/// <summary>
/// Represents a financial transaction (income or expense).
/// The <see cref="ChaveExclusiva"/> property contains a SHA-256 hash
/// computed from Date + Description + Amount, used to detect duplicate
/// imports across CSV/PDF files — identical to the legacy Angular/.NET logic.
/// </summary>
public class Transacao
{
    public Guid Id { get; set; } = Guid.NewGuid();

    public DateTime Date { get; set; }

    public decimal Amount { get; set; }

    public string Description { get; set; } = string.Empty;

    /// <summary>Foreign key to <see cref="Categoria"/>.</summary>
    public Guid? CategoryId { get; set; }

    public Categoria? Categoria { get; set; }

    /// <summary>
    /// SHA-256 deduplication hash over (Date, Description, Amount).
    /// Stored as a 64-character hex string. Generated by <see cref="GerarHash"/>.
    /// </summary>
    public string ChaveExclusiva { get; set; } = string.Empty;

    // ──────────────────────────────────────────────────────────────
    // Domain logic
    // ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Computes and stores the <see cref="ChaveExclusiva"/> SHA-256 hash.
    /// Must be called before persisting a new <see cref="Transacao"/>.
    /// </summary>
    /// <remarks>
    /// Hash input = "yyyy-MM-dd|description|amount" (amount formatted with
    /// invariant culture to two decimal places, matching the legacy app).
    /// </remarks>
    public void GerarHash()
    {
        var input = $"{Date:yyyy-MM-dd}|{Description}|{Amount:F2}";
        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(input));
        ChaveExclusiva = Convert.ToHexString(bytes).ToLowerInvariant();
    }
}
