using System.Globalization;
using System.Security.Cryptography;
using System.Text;

namespace ControleFinanceiroForms.Data.Entities;

/// <summary>
/// Represents a financial transaction (income or expense).
/// The <see cref="ChaveExclusiva"/> property contains a SHA-256 hash
/// computed from Date + Description + Amount, used to detect duplicate
/// imports across CSV/PDF files — identical to the legacy Angular/.NET logic.
/// </summary>
/// <remarks>
/// Use the <see cref="Create"/> factory method to create new instances.
/// The parameterless constructor is reserved for EF Core materialisation.
/// </remarks>
public class Transacao
{
    /// <summary>
    /// EF Core requires a parameterless constructor to materialise entities
    /// from the database. Application code must use <see cref="Create"/> instead.
    /// </summary>
    private Transacao() { }

    /// <summary>
    /// Creates a new <see cref="Transacao"/> with <see cref="ChaveExclusiva"/>
    /// already computed. This is the only way application code should create
    /// transactions — it guarantees the deduplication hash is always set.
    /// </summary>
    public static Transacao Create(DateTime date, string description, decimal amount, Guid? categoryId = null)
    {
        var tx = new Transacao
        {
            Date = date,
            Description = description,
            Amount = amount,
            CategoryId = categoryId
        };
        tx.GerarHash();
        return tx;
    }

    public Guid Id { get; set; } = Guid.NewGuid();

    public DateTime Date { get; set; }

    public decimal Amount { get; set; }

    public string Description { get; set; } = string.Empty;

    /// <summary>Foreign key to <see cref="Categoria"/>.</summary>
    public Guid? CategoryId { get; set; }

    public Categoria? Categoria { get; set; }

    /// <summary>
    /// SHA-256 deduplication hash over (Date, Description, Amount).
    /// Stored as a 64-character hex string. Generated by <see cref="GerarHash"/>.
    /// </summary>
    public string ChaveExclusiva { get; set; } = string.Empty;

    // ──────────────────────────────────────────────────────────────
    // Domain logic
    // ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Computes and stores the <see cref="ChaveExclusiva"/> SHA-256 hash.
    /// Uses <see cref="CultureInfo.InvariantCulture"/> for Amount formatting
    /// to guarantee consistent output regardless of machine locale.
    /// </summary>
    /// <remarks>
    /// Hash input = "yyyy-MM-dd|description|amount" (amount formatted with
    /// invariant culture to two decimal places, matching the legacy app).
    /// </remarks>
    public void GerarHash()
    {
        // FormattableString.Invariant forces all format arguments — including
        // the decimal Amount — to use InvariantCulture, preventing locale-
        // specific separators (e.g., "," in pt-BR) from producing different hashes.
        var input = FormattableString.Invariant($"{Date:yyyy-MM-dd}|{Description}|{Amount:F2}");
        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(input));
        ChaveExclusiva = Convert.ToHexString(bytes).ToLowerInvariant();
    }
}
